### ISSUE TITLE
is drawJpgFile available for non-esp32

### ISSUE THREAD

**Issue by aliceand** [Bodmer/TFT_eFEX#1]
Is void drawJpeg(String filename, int16_t xpos, int16_t ypos, TFT_eSprite *_spr = nullptr) availableon a wemos d1 mini (non-esp32)?

The following code: 

TFT_eFEX  fex = TFT_eFEX(&tft); 
fex.drawJpgFile(SPIFFS, "/Baboon.jpg", 0, 0);

is throwing the following error:
BDemo:52:7: error: 'class TFT_eFEX' has no member named 'drawJpgFile'
   fex.drawJpgFile(SPIFFS, "/Baboon.jpg", 0, 0);

**Comment by Bodmer** [comment]
For historical reasons the function call name is different for the ESP8266 with a file in SPIFFS use:

fex.drawJpeg("/Baboon.jpg", 0, 0);

**Comment by Bodmer** [comment]
I have added an example for the ESP8266L

https://github.com/Bodmer/TFT_eFEX/tree/master/examples

**Comment by aliceand** [comment]
Using fex.drawJpeg works well.  Thank you!
