### ISSUE TITLE
Slow SPIFFS loading time

### ISSUE THREAD

**Issue by PumaFPV** [Bodmer/TFT_eFEX#17]
Hi, I'm trying to load an 960x960 image from spiffs on my esp32 to a st7789 tft screen with a scaling factor and it loads the image in 1,6s which i find to be a lot, is there any way to reduce the loading time?

**Comment by Bodmer** [comment]
Use a program such as MS Paint to scale the picture to the correct size. The decode time is proportional to the pixel area that has to be decoded so by making the image the correct size you will reduce the decode time significantly.
