### ISSUE TITLE
[Request] another drawJpgFile() for displaying the image as the mirror picture on screen.

### ISSUE THREAD

**Issue by TridentTD** [Bodmer/TFT_eFEX#2]
Request the function that can display JPG as the mirror image ( Left <--> Right ) too.

Thank you.

**Comment by Bodmer** [comment]
The simplest approach is to reverse the image in say IrfanView before uploading to the board.

**Comment by TridentTD** [comment]
If any project has tft screen with camera module at the same side of pcb, 
when camera streaming and display on tft screen,  by normal  drawJpg(), 
 on the tft will can't display steaming image as the mirroring image.

If drawJpg()  has  mirror_mode too, tft display will more powerful when displaying. 

Thank you.

**Comment by Bodmer** [comment]
Check  your camera command set, typically you can command the camera to rotate/flip/mirror images.
