### ISSUE TITLE
error: redefinition of 'class TFT_eFEX' when using in custom lib

### ISSUE THREAD

**Issue by flyceo** [Bodmer/TFT_eFEX#20]
I use this class in a custom lib and every try to compile ends with this error message:

`In file included from include/widget.h:2:0,
                 from src/main.cpp:10:
/Users/Roland/.platformio/lib/TFT_eFEX_ID6164/TFT_eFEX.h:63:7: error: redefinition of 'class TFT_eFEX'
 class TFT_eFEX : TFT_eSPI {
       ^
In file included from src/main.cpp:4:0:
/Users/Roland/.platformio/lib/TFT_eFEX_ID6164/TFT_eFEX.h:63:7: error: previous definition of 'class TFT_eFEX'
 class TFT_eFEX : TFT_eSPI {
       ^`

By the way, my lib also uses TFT_eSPI that works absolutely fine

**Comment by flyceo** [comment]
I added

`#ifndef _TFT_eFEXH_
#define _TFT_eFEXH_
...
#endif`

to TFT_eFEX.h to solve that for now.

**Comment by Bodmer** [comment]
Thanks, missed that!

Now fixed.
