### ISSUE TITLE
SwapBytes in void TFT_eFEX::drawJpeg() not working

### ISSUE THREAD

**Issue by OlafWinkler** [Bodmer/TFT_eFEX#25]
Hello,
Great library! Thanks for the development.
I could not activate the SwapBytes-functionality for my ESP32 1.14"-TTGO-LCD-T-Display.
I had to change line 297 to _spr->setSwapBytes(true); from "(false)" in order to make it work.
Is this unfinished development business or am I missing anything?
However, now it is working very nicely.
Thanks again and best regards,
Olaf

**Comment by Bodmer** [comment]
This may be a knock-on effect from a bug correction in TFT_eSPI.

Thanks for raising this, I will investigate further.

**Comment by Bodmer** [comment]
The library has been updated.
