### ISSUE TITLE
Bitmap Image Not Rendering 

### ISSUE THREAD

**Issue by tonyc770** [Bodmer/TFT_eFEX#36]
I am using the TFT_eFEX library for a sprite rotation.
The issue is that even though I can use the line
` fex.drawJpeg("/frame_00.jpg", 0 , 0, &spr);`
and this will render the sprite and I am able to rotate it (image quality is poor) however.

I tried to use a low color (2,4 and 8 bit) bmp of the same jpg image (converted) with this line of code
`fex.drawBmp("/frame_00.bmp", 0 , 0, &spr);`
But the image does not render on the TFT...

Suggestions?
Thanks!

**Comment by Bodmer** [comment]
The rotation uses a simple rotation algorithm so this can prodice jagged pictures, the rotation function built into TFT_eSPI was not really intended for images as interpolation (super sampling) and smoothing (filtating) is required. I don't have the time available to implement this but it is on the todo list.

The rotation functions is for 16 bpp sprites only.
