### ISSUE TITLE
Image problems using TFT_eFEX library

### ISSUE THREAD

**Issue by stephensaid** [Bodmer/TFT_eFEX#37]
Thanks, Bodmer.

I've implemented TFT_eFEX.

I now have a problem with the images. The following image is not right.
![IMG_20210302_205633](https://user-images.githubusercontent.com/1961430/109707375-ff61b580-7b91-11eb-8b69-8cfe05b8e4f6.jpg)

It should look like:
![image](https://user-images.githubusercontent.com/1961430/109707546-30da8100-7b92-11eb-844e-50d4c9cf14f4.png)

I have other images with the same behaviour.

I've tried changing tft.setSwapBytes(true); to tft.setSwapBytes(false); but it has no effect.

Please help.

_Originally posted by @stephensaid in https://github.com/Bodmer/TFT_eSPI/issues/1018#issuecomment-789177553_

**Comment by Bodmer** [comment]
@fotosettore the OP question is for TFT_eFEX, Rotated_Sprite_3 in an example of TFT_eSPI so please raise a new issue.

**Comment by stephensaid** [comment]
Dear Bodmer, 

Hope you are doing well.

It has been a while but had other things to work on and temporarily abandoned this project. I appreciate that you have left this issue open since then.

I updated TFT_eSPI to 2.3.70 and am running TFT_eFEX 0.0.8.

Please view the source [here](https://github.com/stephensaid/JuneRadio/releases/tag/v0.1).

This is very much under construction and I am learning as I go.

As soon as you run the code, the first thing you will see is the splash screen which I have posited in my first post. There are other icons that have the same issue. You might want to replace config_sample.txt with config.txt and edit SSID and Password. Be sure to upload config.txt and most importantly the images and fonts to SPIFFS.

Many thanks in advance.
Stephen

**Comment by stephensaid** [comment]
Hi, 

Changing fex.drawJpeg to fex.drawJpgFile fixed this issue.
