### ISSUE TITLE
Compilation of .ino code when esp_camera.h is included

### ISSUE THREAD

**Issue by kshitijgarg2609** [Bodmer/TFT_eFEX#41]
I am using esp32 cam, I am unable to compile this library. Pls check and I can send you the code too.

![image](https://user-images.githubusercontent.com/48625716/145124003-90af66ec-e665-4ab0-8c22-13d60cb77c39.png)

**Comment by Bodmer** [comment]
This appears to be a problem with the ESP32 board package rather than the TFT_eFEX library.

esp_camera.h is not part of this library.
