### ISSUE TITLE
Landscape images do not display correctly

### ISSUE THREAD

**Issue by Dan018** [Bodmer/TFT_eFEX#7]
ESP32 dev module with ILI9341 display connected to hardware SPI.

When trying to display a SPIFFS jpg image which is 320x240 landscape orientation the image displays 240x240 with a block of background colour filling the rest of the screen.

I've modified the example sketch like this:

void loop()
{
  tft.fillScreen(random(0xFFFF));
  tft.setRotation(1);
  fex.drawJpgFile(SPIFFS, "/image.jpg", 0, 0);
}

It would appear that even though the correct display is selected and set up correctly the image is only displayed to a width of 240px. Portrait orientation is correct and displays fine.

**Comment by Bodmer** [comment]
Thanks for reporting this. I have corrected the library.
