### ISSUE TITLE
Landscape images do not display correctly with function drawJpgFile()

### ISSUE THREAD

**Issue by geprc** [Bodmer/TFT_eFEX#9]
ESP32 dev module with ST7789 display connected to hardware SPI.

When trying to display a SPIFFS jpg image which is 135x135 landscape orientation the image displays smaller with a block of background colour filling the rest of the screen.

I've modified the example sketch like this:
```c++
void loop() {
       tft.fillScreen(random(0xFFFF));
       tft.setRotation(1);
       fex.drawJpgFile(SPIFFS, "/image.jpg", 0, 0);
}
```
Just like this:
![scale](https://user-images.githubusercontent.com/48548067/67478126-08816f00-f68e-11e9-9044-796beb3f4ce0.jpg)
![IMG_20191024_184102](https://user-images.githubusercontent.com/48548067/67478130-091a0580-f68e-11e9-934b-2bfd2268bbf8.jpg)

**Comment by Bodmer** [comment]
It looks your screen has an offset of sbout 40 pixels. A quick fix is to add this offset in your sketch. Instead of 0,0 cordinates, try 40,40

**Comment by geprc** [comment]
40， 40 will be this 
![IMG_20191025_125714](https://user-images.githubusercontent.com/48548067/67544391-d45a8c80-f727-11e9-90b6-d731d0d6f0e4.jpg)
and 40， 70 will be this 
![IMG_20191025_125840](https://user-images.githubusercontent.com/48548067/67544397-dcb2c780-f727-11e9-9cfa-6a3c2a26c36f.jpg)

**Comment by geprc** [comment]
and if i use function drawBmp(), it will be ok,it seems that function drawJpgFile() is not adaptation with st7789,or pixel 240*135

**Comment by Bodmer** [comment]
I have marked this as a bug. Thanks for raising the issue. The display you are using has some offsets so it appears that these are not being used when rendering a jpeg file.

You could try this [new jpeg library](https://github.com/Bodmer/TJpg_Decoder).

I am not in a position to investigate the bug at the moment but will have a look in a few days time.

**Comment by Bodmer** [comment]
I have tested it with the new [Tjpg_Decoder library](https://github.com/Bodmer/TJpg_Decoder) here and this example works: 
[SPIFFS_Jpg_T1.zip](https://github.com/Bodmer/TFT_eFEX/files/3796193/SPIFFS_Jpg_T1.zip)

Using the Tjpg_Decoder library is therefore an option for you until I can track down the bug.

**Comment by Bodmer** [comment]
I think I will be stripping out the ESP32 related jpeg code as it has some rather awkward API, and update the examples to use the [TJpg_Decoder library](https://github.com/Bodmer/TJpg_Decoder) as that uses a later version of the decoder engine.
